#!/bin/bash

set -eEo pipefail

export FOUNDATIONOS_PATH="${FOUNDATIONOS_PATH:-$(cd -- "$(dirname "${BASH_SOURCE[0]}")" && pwd)}"
export FOUNDATIONOS_ROOT="${FOUNDATIONOS_ROOT:-$FOUNDATIONOS_PATH}"
export FOUNDATIONOS_INSTALL="$FOUNDATIONOS_PATH/install"
export FOUNDATIONOS_INSTALL_LOG_FILE="${FOUNDATIONOS_INSTALL_LOG_FILE:-/var/log/foundationos-install.log}"
export OMARCHY_PATH="${OMARCHY_PATH:-$FOUNDATIONOS_PATH}"
export OMARCHY_INSTALL="${OMARCHY_INSTALL:-$FOUNDATIONOS_INSTALL}"
export OMARCHY_INSTALL_LOG_FILE="${OMARCHY_INSTALL_LOG_FILE:-$FOUNDATIONOS_INSTALL_LOG_FILE}"
export PATH="$FOUNDATIONOS_PATH/bin:$PATH"

cd "$FOUNDATIONOS_PATH"

source "$FOUNDATIONOS_INSTALL/helpers/all.sh"
source "$FOUNDATIONOS_INSTALL/preflight/all.sh"
source "$FOUNDATIONOS_INSTALL/packaging/all.sh"
source "$FOUNDATIONOS_INSTALL/config/all.sh"
source "$FOUNDATIONOS_INSTALL/login/all.sh"
source "$FOUNDATIONOS_INSTALL/post-install/all.sh"
